/**
 * This script converts various proxy subscription formats (VLESS, VMess, etc.)
 * into the sing-box JSON configuration format, running entirely in the browser.
 */

// --- Global State & Constants ---
let ORIGINAL_BASE_STRUCTURE=null;
const ALLOWED_SS_METHODS=["chacha20-ietf-poly1305","aes-256-gcm","2022-blake3-aes-256-gcm"];
const DEFAULT_HEADER=`//profile-title: base64:{PROFILE_NAME_BASE64}\n//profile-update-interval: 1\n//subscription-userinfo: upload=0; download=0; total=10737418240000000; expire=2546249531\n//support-url: https://t.me/yebekhe\n//profile-web-page-url: ithub.com/itsyebekhe/PSG`;

// #############################################################################
// Dynamic UI & Core Conversion Logic (Unchanged from previous version)
// #############################################################################
function createInputsForObject(o,c,p){for(const k in o){if(!o.hasOwnProperty(k))continue;const v=o[k];const a=p?`${p}.${k}`:k;const f=document.createElement('div');f.className='form-field';const l=document.createElement('label');l.setAttribute('for',a);l.textContent=k;f.appendChild(l);const w=document.createElement('div');w.className='input-wrapper';let i;const t=typeof v;if(t==='boolean'){i=document.createElement('input');i.type='checkbox';i.checked=v}else if(t==='number'){i=document.createElement('input');i.type='number';i.value=v}else if(t==='string'){i=document.createElement('input');i.type='text';i.value=v}else if(Array.isArray(v)||t==='object'&&v!==null){i=document.createElement('textarea');i.value=JSON.stringify(v,null,2)}if(i){i.id=a;i.dataset.path=a;i.dataset.type=Array.isArray(v)?'array':t;w.appendChild(i)}f.appendChild(w);c.appendChild(f)}}
function buildStructureEditor(d,e){e.innerHTML='';for(const s in d){if(!d.hasOwnProperty(s))continue;if(s==='outbounds')continue;const f=document.createElement('fieldset');f.className='structure-section';const l=document.createElement('legend');l.textContent=s.charAt(0).toUpperCase()+s.slice(1);f.appendChild(l);createInputsForObject(d[s],f,s);e.appendChild(f)}}
function getEditedStructure(){const e=JSON.parse(JSON.stringify(ORIGINAL_BASE_STRUCTURE));document.querySelectorAll('#structure-editor [data-path]').forEach(i=>{const p=i.dataset.path;const t=i.dataset.type;let v;if(t==='boolean'){v=i.checked}else if(t==='number'){v=Number(i.value)}else if(t==='array'||t==='object'){try{v=JSON.parse(i.value)}catch(e){alert(`Invalid JSON format for "${p}". Please check your syntax.`);throw e}}else{v=i.value}setValueByPath(e,p,v)});return e}
function setValueByPath(o,p,v){const k=p.split('.');const l=k.pop();let c=o;for(const e of k){if(!(e in c)){c[e]={}}c=c[e]}c[l]=v}
function decodeUrlSafeBase64(b){let s=b.replace(/-/g,'+').replace(/_/g,'/');const p=s.length%4;if(p){s+='='.repeat(4-p)}return atob(s)}
function detectType(c){const p=["vmess","vless","trojan","ss","tuic","hy2"];for(const r of p){if(c.startsWith(r+"://")){return r}}return null}
function configParse(u){const t=detectType(u);if(!t)return null;try{switch(t){case'vmess':return JSON.parse(atob(u.substring(8)));case'ss':{const l=new URL(u);const n=l.username;let e,s;try{[e,s]=atob(n).split(':',2)}catch(c){try{[e,s]=decodeUrlSafeBase64(n).split(':',2)}catch(a){[e,s]=decodeURIComponent(n).split(':',2)}}const o=l.hash?decodeURIComponent(l.hash.substring(1)):l.hostname;if(typeof s==='undefined')s='';return{'server_address':l.hostname,'server_port':parseInt(l.port,10),'password':s,'encryption_method':e,'name':o}}case'vless':case'trojan':case'tuic':case'hy2':{const r=new URL(u);const p=Object.fromEntries(r.searchParams.entries());return{'scheme':r.protocol.replace(':',''),'hostname':r.hostname,'port':parseInt(r.port,10),'username':decodeURIComponent(r.username),'pass':decodeURIComponent(r.password),'hash':decodeURIComponent(r.hash.substring(1)),'params':p}}default:return null}}catch(e){console.error(`Failed to parse ${t} config:`,u,e);return null}}
class ConfigWrapper{constructor(c){this.type=detectType(c)||'unknown';this.decoded=configParse(c)}isValid(){return this.decoded!==null}getType(){return this.type}getTag(){let t;switch(this.type){case'vmess':t=this.decoded.ps;break;case'ss':t=this.decoded.name;break;default:t=this.decoded.hash;break}return decodeURIComponent(t||'Unknown Tag')}getServer(){switch(this.type){case'vmess':return this.decoded.add;case'ss':return this.decoded.server_address;default:return this.decoded.hostname}}getPort(){let p;switch(this.type){case'ss':p=this.decoded.server_port;break;default:p=this.decoded.port;break}return parseInt(p,10)}getUuid(){switch(this.type){case'vmess':return this.decoded.id;case'vless':case'trojan':case'tuic':return this.decoded.username;default:return''}}getPassword(){switch(this.type){case'trojan':return this.decoded.username;case'ss':return this.decoded.password;case'tuic':return this.decoded.pass;case'hy2':return this.decoded.username;default:return''}}getSni(){switch(this.type){case'vmess':return this.decoded.sni||this.getServer();default:return this.decoded.params?.sni||this.getServer()}}getTransportType(){switch(this.type){case'vmess':return this.decoded.net;default:return this.decoded.params?.type||null}}getPath(){let p;switch(this.type){case'vmess':p=this.decoded.path||'/';break;default:p=this.decoded.params?.path||'/';break}return'/'+(p.startsWith('/')?p.substring(1):p)}getServiceName(){switch(this.type){case'vmess':return this.decoded.path||'';default:return this.decoded.params?.serviceName||''}}get(k,d=null){if(this.type==='ss'&&k==='encryption_method'){return this.decoded.encryption_method}return this.decoded?.[k]??d}getParam(k,d=null){return this.decoded?.params?.[k]??d}}
function vmessToSingbox(c){const o={"tag":c.getTag(),"type":"vmess","server":c.getServer(),"server_port":c.getPort(),"uuid":c.getUuid(),"security":"auto","alter_id":parseInt(c.get('aid'))||0};if(c.getPort()===443||c.get('tls')==='tls'){o.tls=createTlsSettings(c)}if(["ws","grpc","http"].includes(c.getTransportType())){o.transport=createTransportSettings(c);if(o.transport===null)return null}return o}
function vlessToSingbox(c){const o={"tag":c.getTag(),"type":"vless","server":c.getServer(),"server_port":c.getPort(),"uuid":c.getUuid(),"flow":c.getParam('flow')?"xtls-rprx-vision":"","packet_encoding":"xudp"};if(c.getPort()===443||['tls','reality'].includes(c.getParam('security'))){o.tls=createTlsSettings(c);if(c.getParam('security')==='reality'||c.getParam('pbk')){o.flow="xtls-rprx-vision";o.tls.reality={'enabled':true,'public_key':c.getParam('pbk',''),'short_id':c.getParam('sid','')};if(c.getParam('fp')){o.tls.utls=o.tls.utls||{};o.tls.utls.fingerprint=c.getParam('fp')}if(!o.tls.reality.public_key)return null}}if(["ws","grpc","http"].includes(c.getTransportType())){o.transport=createTransportSettings(c);if(o.transport===null)return null}return o}
function trojanToSingbox(c){const o={"tag":c.getTag(),"type":"trojan","server":c.getServer(),"server_port":c.getPort(),"password":c.getPassword()};if(c.getPort()===443||c.getParam('security')==='tls'){o.tls=createTlsSettings(c)}if(["ws","grpc","http"].includes(c.getTransportType())){o.transport=createTransportSettings(c);if(o.transport===null)return null}return o}
function ssToSingbox(c){const m=c.get('encryption_method');if(!ALLOWED_SS_METHODS.includes(m)){return null}return{"tag":c.getTag(),"type":"shadowsocks","server":c.getServer(),"server_port":c.getPort(),"method":m,"password":c.getPassword()}}
function tuicToSingbox(c){return{"tag":c.getTag(),"type":"tuic","server":c.getServer(),"server_port":c.getPort(),"uuid":c.getUuid(),"password":c.getPassword(),"congestion_control":c.getParam("congestion_control","bbr"),"udp_relay_mode":c.getParam("udp_relay_mode","native"),"tls":{"enabled":true,"server_name":c.getSni(),"insecure":!!parseInt(c.getParam("allow_insecure","0")),"alpn":c.getParam('alpn')?c.getParam('alpn').split(','):undefined}}}
function hy2ToSingbox(c){const p=c.getParam('obfs-password');if(!p)return null;return{"tag":c.getTag(),"type":"hysteria2","server":c.getServer(),"server_port":c.getPort(),"password":c.getPassword(),"obfs":{"type":c.getParam('obfs'),"password":p},"tls":{"enabled":true,"server_name":c.getSni(),"insecure":!!parseInt(c.getParam("insecure","0")),"alpn":["h3"]}}}
function createTlsSettings(c){return{"enabled":true,"server_name":c.getSni(),"insecure":true,"utls":{"enabled":true,"fingerprint":"chrome"}}}
function createTransportSettings(c){const t=c.getTransportType();let r=null;switch(t){case'ws':r={"type":"ws","path":c.getPath(),"headers":{"Host":c.getSni()}};break;case'grpc':const s=c.getServiceName();if(!s)return null;r={"type":"grpc","service_name":s};break;case'http':r={"type":"http","host":[c.getSni()],"path":c.getPath()};break}return r}
function convertToSingboxObject(c){const w=new ConfigWrapper(c);if(!w.isValid()){return null}switch(w.getType()){case"vmess":return vmessToSingbox(w);case"vless":return vlessToSingbox(w);case"trojan":return trojanToSingbox(w);case"ss":return ssToSingbox(w);case"tuic":return tuicToSingbox(w);case"hy2":return hy2ToSingbox(w);default:return null}}

// #############################################################################
// Main Processing Logic
// #############################################################################
function generateSingboxProfile(rawInput,inputFormat,baseStructure,profileName,headerTemplate){let configs;if(inputFormat==='base64'){try{configs=atob(rawInput).split(/[\r\n]+/).filter(l=>l.trim()!=='')}catch(e){alert("Error: The input is not valid Base64 content.");return null}}else{configs=rawInput.split(/[\r\n]+/).filter(l=>l.trim()!=='')}const profileStructure=JSON.parse(JSON.stringify(baseStructure));const urlTestOutbound=profileStructure.outbounds.find(o=>o.type==='urltest');const selectorOutbound=profileStructure.outbounds.find(o=>o.type==='selector');configs.forEach(c=>{const s=convertToSingboxObject(c);if(s!==null){profileStructure.outbounds.push(s);const t=s.tag;if(urlTestOutbound?.outbounds)urlTestOutbound.outbounds.push(t);if(selectorOutbound?.outbounds)selectorOutbound.outbounds.push(t)}});const profileNameBase64=btoa(unescape(encodeURIComponent(profileName)));const finalHeader=headerTemplate.replace('{PROFILE_NAME_BASE64}',profileNameBase64);return`${finalHeader}\n\n${JSON.stringify(profileStructure,null,2)}`}

// --- Script Execution (UI Event Handlers) ---
document.addEventListener('DOMContentLoaded',()=>{const c=document.getElementById('convert-btn'),d=document.getElementById('download-btn'),o=document.getElementById('copy-btn'),g=document.getElementById('generate-url-btn'),p=document.getElementById('proxy-configs'),n=document.getElementById('profile-name'),h=document.getElementById('header-editor'),w=document.getElementById('output-wrapper'),j=document.getElementById('output-json'),s=document.getElementById('status-message'),e=document.getElementById('structure-editor'),u=document.getElementById('subscription-url-container'),a=document.getElementById('subscription-url'),b=document.getElementById('copy-url-btn');h.value=DEFAULT_HEADER;fetch('structure.json').then(r=>{if(!r.ok)throw new Error(`Could not load structure.json: ${r.statusText}`);return r.json()}).then(r=>{ORIGINAL_BASE_STRUCTURE=r;buildStructureEditor(r,e);s.textContent='';c.disabled=false}).catch(r=>{console.error("Error loading structure.json:",r);s.textContent=`CRITICAL ERROR: Failed to load 'structure.json'.`;c.disabled=true});c.addEventListener('click',()=>{let t;try{t=getEditedStructure()}catch(r){console.error("Could not generate profile:",r);return}const r=p.value.trim(),i=n.value.trim(),l=document.querySelector('input[name="input-format"]:checked').value,f=h.value;if(!r||!i){alert("Please provide subscription content and a profile name.");return}const m=generateSingboxProfile(r,i,t,i,f);if(m){j.textContent=m;Prism.highlightElement(j);w.classList.remove('hidden');u.classList.add('hidden')}});g.addEventListener('click',async()=>{const r=j.textContent;if(!r){alert("Please generate a profile first.");return}const i=g.textContent;g.textContent='Generating...';g.disabled=true;try{const t=await fetch('https://nekobin.com/api/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:r})});if(!t.ok)throw new Error(`API Error: ${t.statusText}`);const l=await t.json();const f=l.result.key;const m=`https://nekobin.com/raw/${f}`;a.value=m;u.classList.remove('hidden')}catch(t){console.error('Failed to generate URL:',t);alert('Could not generate subscription URL. Please try again later.')}finally{g.textContent=i;g.disabled=false}});const m=(r,i,t)=>{r.addEventListener('click',()=>{const l=(typeof i==='string')?i:i.value||i.textContent;navigator.clipboard.writeText(l).then(()=>{const f=r.textContent;r.textContent=t;r.style.backgroundColor='#28a745';setTimeout(()=>{r.textContent=f;r.style.backgroundColor=''},2000)}).catch(f=>{console.error('Failed to copy text: ',f);alert('Failed to copy text.')})})};m(o,j,'Copied!');m(b,a,'Copied!');d.addEventListener('click',()=>{const r=j.textContent;const i=new Blob([r],{type:'application/json;charset=utf-8'});const t=URL.createObjectURL(i);const l=document.createElement('a');l.href=t;l.download='profile.json';document.body.appendChild(l);l.click();document.body.removeChild(l);URL.revokeObjectURL(t)})});
